Koffieforum/Models/ErrorViewModel.cs
namespace Koffieforum.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Koffieforum/Controllers/ForumController.cs
using Microsoft.AspNetCore.Mvc;

namespace Showcase_Contactpagina.Controllers
{
    public class ForumController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Koffieforum/Controllers/HomeController.cs
using System.Diagnostics;
using Koffieforum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Koffieforum.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Dit om inloggen te verplichten bij de paginas hieronder
        public IActionResult Privacy()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Admin()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Koffieforum/Views/Forum/Index.cshtml
@{
    ViewData["Title"] = "Koffieforum";
}
@section Styles {
    <link rel="stylesheet" href="~/css/koffieforum.css" asp-append-version="true" />
}

<div class="welkomcontainer">
    Welkom op het koffieforum
</div>

<div class="page">
    <div class="infoblok">
        <div class="loginblok">
            Hier login
        </div>

        <div class="categorieblok">
            Hier categorie
        </div>

        <div class="filterblok">
            Hier filters
        </div>
    </div>

    <div class="statblok">
        <div class="postscounter">
            posts counter
        </div>

        <div class="leaderboardposts">
            leaderboard posts
        </div>

        <div class="leaderboardlikes">
            leaderboard likes
        </div>
    </div>

    <div class="postsblok">
        @for (int i = 0; i < 5; i++)
        {
            <div class="post">
                <div class="nameposter">
                    Ruben @i
                </div>

                <div class="textposter">
                    Hier is een bericht 
                </div>    
                
                <div class="postlikecounter">
                    0
                </div>

                <div class="likedislikecontainer">
                    <button class="likebutton">
                        Like!
                    </button>

                    <button class="dislikebutton">
                        Dislike!
                    </button>
                </div>

            </div>
        }        
        
        Derde regel
    </div>
</div>

Koffieforum/Views/Home/Admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="page">
    Admin pagina
</div>

Koffieforum/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="page">
   
   <div>Joeehoeee mensen</div>
</div>

Koffieforum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Koffieforum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Koffieforum.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Forum" asp-action="Index">Koffieforum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                        @* </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forum" asp-action="Index">Koffie Forum</a>
                        </li>
                        @if(User.IsInRole("Admin")){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Admin">Admin pagina</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Koffieforum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>